name: Smoke Test (Windows)

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1

    - name: Install Chocolatey
      run: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Package
      run: choco pack

    - name: Install pGina
      run: choco install pgina

