name: Smoke Test (Windows)

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and install
      run: | 
          choco pack
          choco install pgina

